apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-api
  labels:
    app: demo-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-api
  template:
    metadata:
      labels:
        app: demo-app-api
    spec:
      containers:
      - name: demo-app-api
        image: demo-app-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10 