apiVersion: v1
kind: Service
metadata:
  name: demo-app-api
  labels:
    app: demo-app-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: demo-app-api 