basePath: /
definitions:
  main.Response:
    description: Uma API simples para demonstração de deploy em Minikube.
    properties:
      message:
        type: string
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Uma API simples para demonstração
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Demo App API
  version: "1.0"
paths:
  /:
    get:
      description: Retorna uma mensagem de boas-vindas e a versão da API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Obter informação principal
      tags:
      - info
  /health:
    get:
      description: Endpoint para verificar se a API está funcionando
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Verificação de saúde
      tags:
      - health
schemes:
- http
swagger: "2.0"
